### ISSUE TITLE
Support staticRenderFns

### ISSUE THREAD

**Issue by safrazik** [egoist/babel-plugin-transform-vue-template#5]
Thanks for the awesome plugin. I was writing a similar plugin and then stopped working on it in favor of this plugin.

---

`staticRenderFns` is required  for a template scenario like this:

```html
<section>
  <div>static code</div>
</section>
```
https://forum.vuejs.org/t/vue-compile-what-is-staticrenderfns-render-vs-staticrenderfns/3950
> Static render Functions are used to optimize the render process by essentially caching parts of the DOM tree that are static and therefore can't change. When you call the render function that was generated along with them, it will call these functions to get those static parts.

**Comment by safrazik** [comment]
BTW, I would like to contribute. I would also like to have this [FEATURE: Support template require from external file](https://github.com/egoist/babel-plugin-transform-vue-template/issues/6)

**Comment by egoist** [comment]
Yes, PR welcome.

**Comment by egoist** [comment]
Supported in v0.4
